name: BUILD - Payment Settle Accounts

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-rust:
    uses: ./.github/workflows/common-pipeline.yml
    secrets: inherit

